### ISSUE TITLE
Some problems about fusion points cloud

### ISSUE THREAD

**Issue by progressforever** [YoYo000/MVSNet#11]
您好，很冒昧突然給您來信。我是西北工業大學的一名研究生，最近在研究MVS的過程中遇到了一些post processing方面的問題。
具體問題如下：我在test data 上生成了各圖片的depth map之後，在使用fusibile程序進行編譯的過程中，可以正常運行，但是最終顯示部分結果如下：
p folder is ../data/dtu/calib/
pmvs folder is 
numImages is 49
img_filenames is 49

Fusing points
Processing camera 0
Found 0.00 million points
Processing camera 1
Found 0.00 million points
Processing camera 2
Found 0.00 million points
Processing camera 3
Found 0.00 million points
Processing camera 4
Found 0.00 million points
Processing camera 5
Found 0.00 million points
Processing camera 6
Found 0.00 million points
Processing camera 7
即提示無法找到點，最終生成的final3d_model.plt也只有255字節，在meshlab中顯示無點。已經確定過程序的輸出無誤，也沒有對代碼進行較大改動（除了做了一些路徑上的調整）。想請問您，這個問題是否遇到過，應該如何處理。

希望能盡快得到您的回复，很感謝您在MVS上所做的成果和開源。

**Comment by yao520131415926** [comment]
非常感谢作者优秀的代码！
我目前能够顺利运行这部分代码，但是遇到的问题是：得到的final3d_model并不是期望的那样，是混乱的点云；楼上方便留个联系方式么？交流一下

**Comment by progressforever** [comment]
> 非常感谢作者优秀的代码！
> 我目前能够顺利运行这部分代码，但是遇到的问题是：得到的final3d_model并不是期望的那样，是混乱的点云；楼上方便留个联系方式么？我是研究生，现在正在做这个方向的研究

哈哈哈你可以加我的QQ962360189。可以相互交流

**Comment by progressforever** [comment]
> 你好,
> 
> 不好意思我之前搞错了以为已经回复了你的问题。请问现在点云输出解决了吗？如果点云输出不了可能是fusibile编译安装出了错
> 
> 姚遥

谢谢～点云输出问题已经解决，是我在编译fusibile的过程中未能合理的选择GPU算力导致的，在此也和其他的研究者们提个醒～
谢谢作者的开源～

**Comment by xiankun1995** [comment]
姚遥老师你好！瓜大的同学你好！我也是瓜大的研究生，计算机学院研二的。不知你们是否可以提供一些MVSNet post processing之后的点云结果给我。谢谢~

**Comment by xiankun1995** [comment]
> 
> 
> 我也是学生。我写paper时候的点云好像被覆盖掉了，这两天我从新跑一个给你吧

再次打扰了~如果点云结果跑出来了的话麻烦提供下下载链接，非常感谢！

**Comment by dwangxxx** [comment]
> > 你好,
> > 不好意思我之前搞错了以为已经回复了你的问题。请问现在点云输出解决了吗？如果点云输出不了可能是fusibile编译安装出了错
> > 姚遥
> 
> 谢谢～点云输出问题已经解决，是我在编译fusibile的过程中未能合理的选择GPU算力导致的，在此也和其他的研究者们提个醒～
> 谢谢作者的开源～

学长你好，请问一下你编译生成fusibile可执行文件的时是否只修改了CMakeList文件中GPU算力部分，我的显卡是titan xp，我把算力修改成-gencode arch=compute_61,code=sm_61，但是在进行post processing时还是出现和你一样的问题，所以想请问一下你当时是怎么解决这个问题的，谢谢！！！

**Comment by cuge1995** [comment]
> > 你好,
> > 不好意思我之前搞错了以为已经回复了你的问题。请问现在点云输出解决了吗？如果点云输出不了可能是fusibile编译安装出了错
> > 姚遥
> 
> 谢谢～点云输出问题已经解决，是我在编译fusibile的过程中未能合理的选择GPU算力导致的，在此也和其他的研究者们提个醒～
> 谢谢作者的开源～

请问编译过程如何操作呢？
我是‘cmake.', 'make'
也出现了和你一样的问题

**Comment by ys1215** [comment]
您好，问一下您在编译fusibile的过程中是如何选择GPU算力？

**Comment by ys1215** [comment]
> > 你好,
> > 不好意思我之前搞错了以为已经回复了你的问题。请问现在点云输出解决了吗？如果点云输出不了可能是fusibile编译安装出了错
> > 姚遥
> 
> 谢谢～点云输出问题已经解决，是我在编译fusibile的过程中未能合理的选择GPU算力导致的，在此也和其他的研究者们提个醒～
> 谢谢作者的开源～

您好，问一下您在编译fusibile的过程中是如何选择GPU算力？
