### ISSUE TITLE
accuracy

### ISSUE THREAD

**Issue by jackyangs** [YoYo000/MVSNet#117]
Sorry to bother you, but I would like to know how to calculate the accuracy rate in matlab scripts

**Comment by agenthong** [comment]
Same question, do you know how can I evaluate the result?

**Comment by jackyangs** [comment]
There is an accuracy process on the official website.

**Comment by agenthong** [comment]
> There is an accuracy process on the official website.
> […](#)
> 在 2021年4月6日，下午1:46，agenthong ***@***.***> 写道： ﻿ Same question, do you know how can I evaluate the result? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks!

**Comment by agenthong** [comment]
> There is an accuracy process on the official website.
> […](#)
> 在 2021年4月6日，下午1:46，agenthong ***@***.***> 写道： ﻿ Same question, do you know how can I evaluate the result? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I don't find the process script, can you share the website?

**Comment by agenthong** [comment]
> There is an accuracy process on the official website.
> […](#)
> 在 2021年4月6日，下午1:46，agenthong ***@***.***> 写道： ﻿ Same question, do you know how can I evaluate the result? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I don't find the process script, can you share the website?

**Comment by jackyangs** [comment]
https://github.com/alibaba/cascade-stereo/tree/master/CasMVSNet/evaluations/dtu
you can refer to this.

**Comment by agenthong** [comment]
> https://github.com/alibaba/cascade-stereo/tree/master/CasMVSNet/evaluations/dtu
> you can refer to this.

Thanks a lot!  Do you have wechat or something that we can talk about this repo?

**Comment by jackyangs** [comment]
Are you a Chinese?

**Comment by agenthong** [comment]
> Are you a Chinese?
> […](#)
> 在 2021年4月7日，上午11:25，agenthong ***@***.***> 写道： ﻿ https://github.com/alibaba/cascade-stereo/tree/master/CasMVSNet/evaluations/dtu you can refer to this. Thanks a lot! Do you have wechat or something that we can talk about this repo? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

dui

**Comment by jackyangs** [comment]
我加你微信吧

**Comment by agenthong** [comment]
> 我加你微信吧
> […](#)
> 在 2021年4月7日，上午11:36，agenthong ***@***.***> 写道： ﻿ Are you a Chinese? … 在 2021年4月7日，上午11:25，agenthong @.***> 写道： ﻿ https://github.com/alibaba/cascade-stereo/tree/master/CasMVSNet/evaluations/dtu you can refer to this. Thanks a lot! Do you have wechat or something that we can talk about this repo? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. dui — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

hzc-luvsbasketball

**Comment by crazycodebiu** [comment]
> Sorry to bother you, but I would like to know how to calculate the accuracy rate in matlab scripts
我也遇到相同的问题，请问可以加您微信，向您请教一下吗，我的微信号是acba777

**Comment by BiaBibii** [comment]
Hello, could you help me about the matlab scripts? I tried to run BaseEvalMain and I get some issues
