### ISSUE TITLE
How to test the model on other images

### ISSUE THREAD

**Issue by seul0724** [YoYo000/MVSNet#12]
I have trained and tested the model on the given dataset, and the experimental result is pretty good. 

However, when I test the model on my own data, it seems not to work. 

My testing procedure is:
1. Collect a set of images using a camera with fixed focus;
2. Get the camera parameters and matching information through VisualSFM, and fill the information in the corresponding  cam.txt and pair.txt;
3. Get the depth range based on point clouds produced by  VisualSFM, and calculate the depth interval as  (max_depth-min_depth)/192. In my case, the min_depth is 0.0, the interval is 0.01, and I have filled the information in each cam.txt;
4. Set the max_w and max_h in the test script based on my image size (width:1152, height:768).

However, in the last depthfusion step, 0.00 million points are found. By visualizing the pfm files, I find that the probabilities are all 0.020833334. 

I am new to this field and cannot figure out where is wrong. Could anyone be so nice to help me?

**Comment by YoYo000** [comment]
Hi @seul0724 , could you visualize the initial depth map?

BTW @KevinCain have discussed how to prepare the input from Colmap in this issue:

https://github.com/YoYo000/MVSNet/issues/8#issue-369981864

**Comment by seul0724** [comment]
Hi Yao , 
thank you very much for your reply.


I have put the original and visualization of the initial depth maps in the attachment. The depth_min was 0.0, and the depth_interval was 0.01. As we can see, the values of the initial depth maps were all "0.0", and in the last depthfusion step, 0.00 million points were found. 


After several trials, I have got a rough reconstruction result by setting depth_min to 0.0012 and depth_interval to 0.075.  The ply file and visualization result are also attached in the files. As we can see, the results (mvsnet in the attachment) seem inferior to that of VisualSFM (sfm in the attachment). More importantly, the parameters are set by exploring different values and do to match the depth range (the depth range is got by observing point clouds produced by Viusal SFM). Besides, I find that the reconstruction result is very sensitive to the depth_min parameter, and a small offset in depth_min can produce very different reconstruction result. 


I used to do research on object detection in 2D images and I am new to this field.  I get so confused on how to set the parameters for our own images and how to improve the results. Maybe something is wrong, and I hope you can help me to figure it out.


Thank you very much for your patience.








| |
韩婧
|
|
jinghan_0724@163.com
|
签名由网易邮箱大师定制
On 11/4/2018 09:37，Yao Yao<notifications@github.com> wrote：

Hi @seul0724 , could you visualize the initial depth map?

BTW @KevinCain have discussed how to prepare the input from Colmap in this issue:

#8 (comment)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

从网易邮箱大师发来的云附件
attachment.rar(41.4MB,2018年11月20日 16:29 到期)
下载

**Comment by YoYo000** [comment]
Hi,

From my guess it is the problem of the depth range. MVSNet is unable to reconstruct the scenes out of the input depth range, so we must ensure that the given depth_min and depth_interval are corresponding to the SfM system. Note that large depth_interval may also affect the reconstruction quality.

BTW I am planning to transfer the SfM results from other software (e.g., Altizure and Colmap) to MVSNet input in the near future.

Best,
Yao

**Comment by seul0724** [comment]
I have tried to set the depth_min and depth_interval  based on the depth range given by the sfm system, but I failed to get the desired result. Is there anyway to get the correct depth_min and depth_interval parameters?

**Comment by YoYo000** [comment]
@seul0724 if you wish you could send me the data, and I can apply our sfm and camera selection methods to help reconstruct the point cloud result.

**Comment by seul0724** [comment]
I have tried colmap as discussed in another issue, and the camera parameters extracted from colmap produce better results than visualsfm. Could you please share your way to extract camera parameters and depth ranges?
