### ISSUE TITLE
fusible build error in win10 visual 2019

### ISSUE THREAD

**Issue by lilipopololo** [YoYo000/MVSNet#126]
when I build this version of fusible(edited by author?) in vs 2019, opencv 4.5.2,（openMP 2.0）, I found in mathUtils.h 

``
#if defined(_WIN32)

static float roundf ( float val ) {
    return floor ( val+0.5f );
};
#endif
``

C2491:definition of dllimport function not allowed

so I remove it and revise it to
``
#if defined(_WIN32)
static float roundf(float val);
#endif
``
can it work? And what can i do for this.
(I can build the origin fusible in win, but I think fusible edited by author may work better)

**Comment by lilipopololo** [comment]
I change `size_t` to `long int` as same as the origin edition in displayUtils.h(105 9), and change `static float` to `static inline float`(mathUtils.h14 8), I can build fusible.exe in win10, but I can't use it to generate the point cloud and depth maps, I dont know why.

**Comment by lilipopololo** [comment]
During I use the origin version of fusible , commander always show
 `"Not enough space to save points". `
perhaps it may affect the quality of generated depthmaps and point clouds

**Comment by lilipopololo** [comment]
搞错了，居然是opencv出问题。我整个没想到

**Comment by AsDeadAsADodo** [comment]
> 搞错了，居然是opencv出问题。我整个没想到

请问是什么问题？我用fusibile出现Segmentation fault core dumped
