### ISSUE TITLE
Acess denied to download DTU dataset from goolge drive

### ISSUE THREAD

**Issue by YeonsungJung** [YoYo000/MVSNet#135]
@YoYo000 
Hi, i tried to download DTU dataset from google drive but there is a following error,

        Too many users have viewed or downloaded this file recently. Please
        try accessing the file again later. If the file you are trying to
        access is particularly large or is shared with many people, it may
        take up to 24 hours to be able to view or download the file. If you
        still can't access a file after 24 hours, contact your domain
        administrator
        
Could you please check google drive to downlaod DTU dataset again?

**Comment by YeonsungJung** [comment]
solved

**Comment by FeiiYin** [comment]
Hi, I face the problem as below:
```
访问 doc-0o-bg-docs.googleusercontent.com 被拒绝你没有查看此页面的用户权限。
HTTP ERROR 403
```
```
Access to doc-0o-bg-docs.googleusercontent.com denied You do not have user permission to view this page.
HTTP ERROR 403
```
How to solve that? Thanks in advance.
Could you please check google drive to downlaod DTU dataset again?

**Comment by aditya-vora** [comment]
Hello, I am facing similar issue. Can you please reactivate the link.
