### ISSUE TITLE
一些关于D设置的问题

### ISSUE THREAD

**Issue by progressforever** [YoYo000/MVSNet#16]
您好，感谢您的开源，我有一些D设置方面的问题想问您。
首先，我观察到在训练中，您对参数的设置为640x512x128，interval=1.6。在测试中您的设置为1100x860x192，interval=0.8。而就您文中而言，您又用了1600x1184x256,interval=0.8来测试得出最终结果。在测试中不同的D（192,256）却有着同样的interval（0.8），会不会对结果造成影响呢？
其次，我想请问，D的选择和图像分辨率的大小是成一个正比的关系？如果说我在640*540的图像上用D=256.interval=0.8训练的话，是不是就不应该了。这个D的选择是您经过多次实验而得出的吗？
再次感谢您的开源～希望得到您的回复～

**Comment by YoYo000** [comment]
internal越小结果应该会越准确。

training我没有仔细做过比较，不过D=128也可以得到好的结果，并且速度更快需要的显存也更小。

testing的话我在supplimentary material中有对比实验。

**Comment by YoYo000** [comment]
Hi, 

For training @shubhamag have done an interesting study (https://github.com/YoYo000/MVSNet/issues/17#issue-392437668) on depth sample number.
