### ISSUE TITLE
Minimum hardware requirements to train/test

### ISSUE THREAD

**Issue by pawlusmall** [YoYo000/MVSNet#18]
Hi,

First of all, congratulations for you excellent work and contribution to MVS.

I've tried to test the code with an Intel 8700k, 16GB RAM and Nvidia 1070 8GB VRAM without success using both tensorflow-cpu and tensorflow-gpu.

The problem is resource exhaustion, the system gets out of RAM or VRAM few seconds after program execution.

My first idea to fix it was decreasing batch size, but it is already 1.

Do I need a better graphics card to run your code? Could I tune some params to make it work with my current computer setup?

Thanks.

**Comment by pawlusmall** [comment]
Got it working with:

- max_w = 680
- max_h = 480
- max_d = 160

Results are not as fine as yours but it's something.

Thanks.

**Comment by nickponline** [comment]
I am trying to run the Tanks and Temples dataset with:

> max_d = 1090
> max_h = 1056
> max_d = 256

I have 4x 1080 Ti's does the test.py script support multiple GPUs?
