### ISSUE TITLE
How do you compute the memory required?

### ISSUE THREAD

**Issue by nickponline** [YoYo000/MVSNet#19]
How can I compute the memory required to do inference with MVSNet as a function of `max_w`, `max_h`, `max_d`, `interval_scale` and possibly some other parameters? 

As it seems that as `DEPTH_INTERVAL` decreases the network uses more memory.

**Comment by YoYo000** [comment]
Hi  Nick,

The GPU requirement is roughly linear to the cost volume size, and using 16GB memory GPU could deal with a maximum input size of H x W x D = 1600 x 1200 x 256. Currently MVSNet is hard to be scaled up to very large scale scenes. But if you want you could try retrain the model with less feature channels / pyramid scales for the 3D CNN part.

**Comment by YoYo000** [comment]
No, the memory should be independent to the two params.

**Comment by mazeyu** [comment]
Hi, I am wondering if you use the command "nvidia-smi" or some package to report the memory. Thank you!
