### ISSUE TITLE
OOM memory issue

### ISSUE THREAD

**Issue by eddienewton** [YoYo000/MVSNet#21]
Hi, 

I had a question regarding running the 'family' image set from Tanks and Temples.  I'm using a P100 on a Google Cloud compute engine machine.  According to the initial logs, I have 15.5GB of GPU memory free (see below).  I'm running into the OOM memory issue when running the following command:

`python test.py --dense_folder /home/ubuntu/images/family/ --max_d 256 --max_w 1760 --max_h 960`

The dimensions used are less than the 1920 x 1056 x 256 dimensions you used.  Is there anything else you had to do to get MVSNet to work?  My volume is approximately 83% of what you tested.

Did you use a P100 on a compute engine?  Or did you use the Google Cloud ML platform without server?

Thanks again!
Ed

> sample number:  152
> 2D with 32 filters
> 2D with 32 filters
> 2D with 32 filters
> 2D with 32 filters
> 2D with 32 filters
> 3D with 8 filters
> 2019-01-13 14:00:02.865478: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2019-01-13 14:00:03.482779: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2019-01-13 14:00:03.483170: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
> name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
> pciBusID: 0000:00:04.0
> totalMemory: 15.90GiB freeMemory: 15.53GiB
> 2019-01-13 14:00:03.483203: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
> 2019-01-13 14:00:14.140075: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-01-13 14:00:14.140130: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
> 2019-01-13 14:00:14.140137: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
> 2019-01-13 14:00:14.140357: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15051 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)

**Comment by YoYo000** [comment]
I used Google Cloud ML platform.

**Comment by nickponline** [comment]
@eddienewton If speed is not an issue, inference on CPU runs at about 20%  of the speed. Caveat is I think there is some issue with the output that's preventing the fusion running correctly. 

https://github.com/YoYo000/MVSNet/issues/22

**Comment by eddienewton** [comment]
@nickponline thanks for the tip!  I'll give it a try.  Will let you know if I encounter a similar issue with fusion step.

**Comment by eddienewton** [comment]
@YoYo000 thanks for the info!  Closing now.
