### ISSUE TITLE
CPU inference seg faults in depthfusion.py

### ISSUE THREAD

**Issue by nickponline** [YoYo000/MVSNet#22]
I noticed that the outputs generated from running `test.py` using just CPU are different from the GPU and cause `depthfusion.py` to fail with `segmentation fault`.

This is the the TnT Horse dataset using `max_w, max_w, max_h = (1152, 672, 256)`

Here are the depth maps produced using the GPU:
https://www.dropbox.com/s/6nwbic9884ulwtt/depths_mvsnet_gpu.zip?dl=0

and these are the CPU ones:
https://www.dropbox.com/s/jozz38morx0pxd2/depths_mvsnet_cpu.zip?dl=0

Not exactly sure what's different between them that causes `depthfusion.py` to seg fault with the CPU dataset.

I wanted to try using the CPU because I had access to more memory even though it's slower.

**Comment by eddienewton** [comment]
@nickponline if you upload the pair.txt file used, I can try my own fusion executable.  I'll report back with what caused the issue.

**Comment by nickponline** [comment]
@eddienewton Thanks! Here is the link: 

https://www.dropbox.com/s/frcyheaoo3z2ah7/pair.txt?dl=0

**Comment by eddienewton** [comment]
@nickponline both work with my code, and are within 16 total vertices apart.  Here are the scans and a screenshot of them side-by-side.  

I'm guessing depthfusion.py is crashing because of a misspelled path.  

Hope this has helped.

![comparison](https://user-images.githubusercontent.com/43154795/51145964-40f44280-180a-11e9-9681-0d6e9f5edf2f.jpg)
[fusion_ply_files.zip](https://github.com/YoYo000/MVSNet/files/2757337/fusion_ply_files.zip)

**Comment by nickponline** [comment]
Hmmm seems to be working now. Maybe it's because I'm running is straight after the inference which isn't releasing memory properly .. Not sure what else it could be. Can close.

**Comment by eddienewton** [comment]
@nickponline glad it worked out.  From recollection, tensorflow won't release the GPU until the parent python script completes.  This probably caused your issue.  

Out of curiosity, was your fused point-cloud similar to what I posted?

**Comment by nickponline** [comment]
@eddienewton Yes, here it is: https://www.dropbox.com/s/03qerx8braymdp1/final3d_model.ply?dl=0

**Comment by eddienewton** [comment]
@nickponline thanks!  Was this done with the depth data above?  I might have a bug in my implementation if so.  Or was this done with large depthmaps?  

Your # of vertices is about 20X that of mine (2.7M vs 127K).  

Thanks in advance.
