### ISSUE TITLE
Testing on Aerial Dataset data

### ISSUE THREAD

**Issue by cecca46** [YoYo000/MVSNet#26]
Hello,

I am currently trying to test MVSNet on the Aerial dataset. The scene I am using for testing contains 226 images of 1280 × 720. I resized them to 1280 × 900 prior using MVSNet. 
The 00000000_cam.txt looks like this:

extrinsic
-0.781098 0.61589 0.102788 -1.16349
0.278708 0.491198 -0.825255 -1.00648
-0.558756 -0.615958 -0.555327 16.4424
0.0 0.0 0.0 1.0

intrinsic
2307.27 0 640
0 2307.27 360
0 0 1

8 0.05

I also added information in the pair.txt file by computing feature similarly between the pictures and selecting the top 10 results (for that I simply computed the RMSE between images and choose the lowest 10 results).  The depth range for the input images is between 8~17. So I select a depth_interval of 0.05. I am also using a max_d of 192 and interval_scale of 1. 
The output looks:
![image](https://user-images.githubusercontent.com/22442873/52354981-5afbfc00-2a29-11e9-95a4-57da950e6877.png)
Clearly, the result is very off the original input image which looks like: 
![image](https://user-images.githubusercontent.com/22442873/52355112-9c8ca700-2a29-11e9-9405-86183f0e6d33.png)

If you could please provide some guidance about the depth reconstruction or whether you ever assessed MVSNet on Aerial it would be great!

Thank you!

**Comment by YoYo000** [comment]
Hi @cecca46,

How did you resize the images? I am not sure whether the test script handles f_x != f_y so please keep the aspect ratio when you do the resizing. You could use cropping to change the aspect ratio. (For your case 1280x720 -> 1600x900 -> 1280x900)

Also reminber to **change camera intrinsics** after resizing / cropping images. You may refer to the preprocessing part in test.py for implementations. 

Yao
