### ISSUE TITLE
ROI via principal point shift and focal length scaling

### ISSUE THREAD

**Issue by KevinCain** [YoYo000/MVSNet#27]
Here I have MVSNet camera information for a 4000x3000 image:

```
extrinsic
0.999804 -0.019096 -0.00518646 -1.1364
0.0189494 0.999457 -0.0269683 -1.71932
0.00569863 0.0268648 0.999623 1.65699
0.0 0.0 0.0 1.0

intrinsic
4806.29 0 2000
0 4806.29 1500
0 0 1

2.56448 0.0640064
```

The focal length (4806.29 pixels) and principle point (centered) are shown in bold in the above intrinsic matrix:

**4806.29** 0 **2000**
0 **4806.29** **1500**
0 0 1

Next we crop the input image to its top left quadrant (one quarter of our original image, now 2000x1500) and compensate in the intrinsics by _doubling the focal length_ and _shifting the principal point_ as follows:

**9612.58** 0 **0**
0 **9612.58** **0**
0 0 1

The idea is to break the existing camera into parts, creating an arbitrary region of interest.

When I run MVSNet on the above, I get sensible results for the initial pose but unexpected results for the upper left quadrant intrinsics.

Is this a sound approach?  Does MVSNet need all input images to be the same size?

**Comment by YoYo000** [comment]
@KevinCain MVSNet I did not explicitly handle different image sizes, so you may pay attention to this part when using the provided script.

If you are using the top-left image, I think you only need to change the image size but the intrinsic should remain unchanged? 

BTW for the top-right image patch, the intrinsic is:

**4806.29** 0 **0**
0 **4806.29** **1500**
0 0 1

**Comment by KevinCain** [comment]
Thanks, @YoYo000, you're correct in both cases.  ;-)

I assume that when using the principal point to shift the ROI, during sparse reconstruction I should not try to estimate the principal point.

**Comment by KevinCain** [comment]
While the principal point in camera space is near image center, the image coordinates (u, v) origin is often in top left (OpenCV) or bottom left.

What assumption does MVSNet make for the principle point origin for image space?  

As shown below, I believe I'm incorrectly assuming that it's the bottom right.  Considering 2054x1502 quadrants from 4108x3004 images, for the four quadrants I have the following intrinsics, which seem to be wrong:

Top left quadrant:
4714.29 0 **2054**
0 4714.29 **1502**
0 0 1

Top right quadrant:
4714.29 0 **0**
0 4714.29 **1502**
0 0 1

Bottom left quadrant:
4714.29 0 **2054**
0 4714.29 **0**
0 0 1

Bottom right quadrant:
4714.29 0 **0**
0 4714.29 **0**
0 0 1

**Comment by YoYo000** [comment]
The estimated u, v are not necessarily equal to W/2, H/2. 

Top left quadrant:
f 0 **u**
0 f **v**
0 0 1

Top right quadrant:
f 0 **u - W/2**
0 f **v**
0 0 1

Bottom left quadrant:
f 0 **u**
0 f **v - H/2**
0 0 1

Bottom right quadrant:
f 0 **u - W/2**
0 f **v - H/2**
0 0 1

**Comment by KevinCain** [comment]
Thanks, @YoYo000 for your quick reply!

Assuming W=4108, H=3004, u=2054, v=1502, your formulas match the values I give above.

Using these intrinsic values with MVSNet yields incorrect results except in top left quadrant (same intrinsics, as you pointed out).  Note that the results look wrong whether I'm _doubling the focal length_ (see quote below) as I noted before, _or using the same focal length_ for the cropped images as for the original images.

Should the source image be the image cropped to a quadrant, or the full sized input for which the camera pose was computed?

> Top left - W=4108, H=3004, u=2054, v=1502:
> 9428.58 0 2054 (u = 2054)
> 0 9428.58 1502 (v = 1502)
> 0 0 1
> 
> Top right - W=4108, H=3004, u=2054, v=1502:
> 9428.58 0 0 (u - W/2 = u - 2054 = 2054 - 2054 = 0)
> 0 9428.58 1502 (v = 1502)
> 0 0 1
> 
> Bottom left - W=4108, H=3004, u=2054, v=1502:
> 9428.58 0 2054 (u = 2054)
> 0 9428.58 0 (v - H/2 = 1502 - 3004/2 = 1502 - 1502 = 0)
> 0 0 1
> 
> Bottom right - W=4108, H=3004, u=2054, v=1502:
> 9428.58 0 0 (u - W/2 = u - 4108/2 = 2054 - 2054 = 0)
> 0 9428.58 0 (v - H/2 = 1502 - 3004/2 = 1502 - 1502 = 0)
> 0 0 1

**Comment by KevinCain** [comment]
To illustrate my above confusion, here are MVSNet results for the familiar DTU 'scan9' dataset.

Image (left), vis (center), and prob-vis (right):
![00000000](https://user-images.githubusercontent.com/5424003/53135887-cd90cf80-3531-11e9-9b37-16aa548b9491.jpg) ![00000000-vis](https://user-images.githubusercontent.com/5424003/53135961-15175b80-3532-11e9-808c-6186fdbbd141.jpg) ![00000000_prob-vis](https://user-images.githubusercontent.com/5424003/53135889-d5e90a80-3531-11e9-9ebe-dc006f09fdca.jpg)

The camera file is as follows (note no attempt to estimate principal point):

> extrinsic
> 0.910293 0.164153 -0.380028 1.48815
> -0.226191 0.966094 -0.124497 -0.872257
> 0.346706 0.199288 0.916558 1.33805
> 0.0 0.0 0.0 1.0
> 
> intrinsic
> 2888.84 0 800
> 0 2888.84 600
> 0 0 1
> 
> 4.41871 0.0212743

Below, my attempt to process a quadrant of the image above.  The top left quadrant uses the same intrinsics, as @YoYo000 notes above.

**Top left quadrant**
Cropped input image (left), initial vis for readability (center) and prob-vis (right):

![00000000](https://user-images.githubusercontent.com/5424003/53136452-eef2bb00-3533-11e9-9667-81e02510913f.jpg) ![00000000_init-vis](https://user-images.githubusercontent.com/5424003/53136454-f0bc7e80-3533-11e9-8f80-15dfa7e50a4f.jpg) ![00000000_prob-vis](https://user-images.githubusercontent.com/5424003/53136457-f1edab80-3533-11e9-81fd-69fabfbe1b7e.jpg)

> intrinsic
> 2888.84 0 800
> 0 2888.84 600
> 0 0 1
> 

**Top right quadrant**
Cropped input image (left), initial vis for readability (center) and prob-vis (right):
![00000000](https://user-images.githubusercontent.com/5424003/53136110-9242d080-3532-11e9-8dc3-897cd8ab31c0.jpg) ![00000000_init-vis](https://user-images.githubusercontent.com/5424003/53136112-940c9400-3532-11e9-80a1-47ed52c6d187.jpg) ![00000000_prob-vis](https://user-images.githubusercontent.com/5424003/53136114-953dc100-3532-11e9-871a-c362f75becf1.jpg)

> intrinsic
> 2888.84 0 800
> 0 2888.84 0
> 0 0 1
> 

The top full size and top left quadrant depths look reasonable to me, but not the top right.

Clearly I'm making a fundamental mistake -- if possible, can you attempt to duplicate?

**Comment by YoYo000** [comment]
Do you crop the source images as well?

**Comment by KevinCain** [comment]
As I noted above, @YoYo000's principal point offsets are correct -- my results above reflect incorrect intrinsics for some of the neighbors involved in the depth computation.
