### ISSUE TITLE
About training, I can't make it work

### ISSUE THREAD

**Issue by kakaxi314** [YoYo000/MVSNet#3]
Thanks for your work and code.
I encounter some problems when I train the mvsnet.
1. I downloaded the preprocessed DTU training data from your link, however, there's no **train** folder in the **Cameras** folder. Also, I find the camera parameters seem correspond to the original image size. So I modified camera parameters as the process in the paper, resize into 800x600 and center crop the 512x640.
finally, the 00000000_cam.txt should look like this, is it right?
>extrinsic
0.970263 0.00747983 0.241939 -191.02
-0.0147429 0.999493 0.0282234 3.28832
-0.241605 -0.030951 0.969881 22.5401
0 0 0 1
>
>intrinsic
1446.1650390625 0.0 331.6025085449219
0.0 1441.5899658203125 265.5354919433594
0.0 0.0 1.0
>
>425 2.5

2. I have tried training the network by using the original train.py. Also, I tried the hyperparameter listed in the paper with `max_d=256`, `interval_scale=0.8`. However, the loss decreases very slow and at 70000 iters, the model doesn't work at all. I also found that the size of my model is very small with around 20MB, but the model you provided is almost 200MB. 

I'm sorry that I'm new to tensorflow, it's a little hard for me to check the problems out. 
Could you please give me some suggestions in detail about training this network.

**Comment by shubhamag** [comment]
Same issue as 1). I think the dataset linked is not split into train-validation which is what the code expects..

**Comment by YoYo000** [comment]
Hi both,

It seems like it is the problem of the training cameras.

I will fix the training when I come back from ECCV, for now could you try these pre-processed cameras:

https://drive.google.com/open?id=1MsWaUs23QFxOfTw2RI1HGclyypuKchPn

@kakaxi314 The cameras are used for building the cost volume, so you need to further downsize them by 4.

Yao

**Comment by kakaxi314** [comment]
@YoYo000 Now, it works, thanks.

**Comment by philleer** [comment]
Hi, @YoYo000 , when I run the train.py script
```
Create a log folder and a model folder in wherever you like to save the training outputs. Set the log_dir and save_dir in train.py correspondingly
Train MVSNet (GTX1080Ti): python train.py --regularization 'GRU'
Train R-MVSNet (GTX1080Ti): python train.py --regularization '3DCNNs'
```
I came across some problem as follows:
```
~/MVSNet/mvsnet$ python train.py --regularization 'GRU'
```
```
Training MVSNet with 3 views
sample number:  54194 
2D UNet with 32 channel output
2D UNet with 32 channel output
2D UNet with 32 channel output
2019-03-25 12:42:06.482637: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-03-25 12:42:06.565576: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:895] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-03-25 12:42:06.565897: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties:
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:01:00.0
totalMemory: 7.93GiB freeMemory: 7.62GiB
2019-03-25 12:42:06.565925: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-03-25 12:43:12.610862: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/GRU/model.ckpt-0
2019-03-25 12:43:12.611048: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/GRU/model.ckpt-0
2019-03-25 12:43:12.611099: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/GRU/model.ckpt-0
2019-03-25 12:43:12.611138: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/GRU/model.ckpt-0
2019-03-25 12:43:12.611176: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/GRU/model.ckpt-0
2019-03-25 12:43:12.611213: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/GRU/model.ckpt-0
...
2019-03-25 12:43:12.622409: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/GRU/model.ckpt-0
2019-03-25 12:43:12.622439: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/GRU/model.ckpt-0
Traceback (most recent call last):
  File "train.py", line 353, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "train.py", line 348, in main
    train(sample_list)
  File "train.py", line 297, in train
    restorer.restore(sess, '-'.join([pretrained_model_path, str(FLAGS.ckpt_step)]))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1686, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/GRU/model.ckpt-0
         [[Node: save_1/RestoreV2_151 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_151/tensor_names, save_1/RestoreV2_151/shape_and_slices)]]
         [[Node: save_1/RestoreV2_37/_1923 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1172_save_1/RestoreV2_37", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op u'save_1/RestoreV2_151', defined at:
  File "train.py", line 353, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "train.py", line 348, in main
    train(sample_list)
  File "train.py", line 296, in train
    restorer = tf.train.Saver(tf.global_variables())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1239, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1248, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1284, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 765, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 428, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 268, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1031, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/GRU/model.ckpt-0
         [[Node: save_1/RestoreV2_151 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_151/tensor_names, save_1/RestoreV2_151/shape_and_slices)]]
         [[Node: save_1/RestoreV2_37/_1923 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1172_save_1/RestoreV2_37", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
```
I don't know what problem it is. And i have tried the solution such as
[Unsuccessful TensorSliceReader constructor](https://github.com/tensorflow/tensorflow/issues/7547) or [as suggested by ppwwyyxx](https://github.com/tensorflow/tensorflow/issues/6082#issuecomment-265055615)
but it still not work...
what should i do, i am a newer to tensorflow, please help me. Thx very much!

**Comment by philleer** [comment]
> Hi, @YoYo000 , when I run the train.py script
> 
> ```
> Create a log folder and a model folder in wherever you like to save the training outputs. Set the log_dir and save_dir in train.py correspondingly
> Train MVSNet (GTX1080Ti): python train.py --regularization 'GRU'
> Train R-MVSNet (GTX1080Ti): python train.py --regularization '3DCNNs'
> ```
> I came across some problem as follows:
> 
> ```
> ~/MVSNet/mvsnet$ python train.py --regularization 'GRU'
> ```
> ```
> Training MVSNet with 3 views
> sample number:  54194 
> 2D UNet with 32 channel output
> 2D UNet with 32 channel output
> 2D UNet with 32 channel output
> 2019-03-25 12:42:06.482637: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
> 2019-03-25 12:42:06.565576: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:895] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2019-03-25 12:42:06.565897: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties:
> name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
> pciBusID: 0000:01:00.0
> totalMemory: 7.93GiB freeMemory: 7.62GiB
> 2019-03-25 12:42:06.565925: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
> 2019-03-25 12:43:12.610862: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/GRU/model.ckpt-0
> 2019-03-25 12:43:12.611048: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/GRU/model.ckpt-0
> 2019-03-25 12:43:12.611099: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/GRU/model.ckpt-0
> 2019-03-25 12:43:12.611138: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/GRU/model.ckpt-0
> 2019-03-25 12:43:12.611176: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/GRU/model.ckpt-0
> 2019-03-25 12:43:12.611213: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/GRU/model.ckpt-0
> ...
> 2019-03-25 12:43:12.622409: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/GRU/model.ckpt-0
> 2019-03-25 12:43:12.622439: W tensorflow/core/framework/op_kernel.cc:1198] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/GRU/model.ckpt-0
> Traceback (most recent call last):
>   File "train.py", line 353, in <module>
>     tf.app.run()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run
>     _sys.exit(main(argv))
>   File "train.py", line 348, in main
>     train(sample_list)
>   File "train.py", line 297, in train
>     restorer.restore(sess, '-'.join([pretrained_model_path, str(FLAGS.ckpt_step)]))
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1686, in restore
>     {self.saver_def.filename_tensor_name: save_path})
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
>     run_metadata_ptr)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1344, in _do_run
>     options, run_metadata)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1363, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/GRU/model.ckpt-0
>          [[Node: save_1/RestoreV2_151 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_151/tensor_names, save_1/RestoreV2_151/shape_and_slices)]]
>          [[Node: save_1/RestoreV2_37/_1923 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1172_save_1/RestoreV2_37", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
> 
> Caused by op u'save_1/RestoreV2_151', defined at:
>   File "train.py", line 353, in <module>
>     tf.app.run()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run
>     _sys.exit(main(argv))
>   File "train.py", line 348, in main
>     train(sample_list)
>   File "train.py", line 296, in train
>     restorer = tf.train.Saver(tf.global_variables())
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1239, in __init__
>     self.build()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1248, in build
>     self._build(self._filename, build_save=True, build_restore=True)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1284, in _build
>     build_save=build_save, build_restore=build_restore)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 765, in _build_internal
>     restore_sequentially, reshape)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 428, in _AddRestoreOps
>     tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 268, in restore_op
>     [spec.tensor.dtype])[0])
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1031, in restore_v2
>     shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
>     op_def=op_def)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
>     self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
> 
> NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoint/GRU/model.ckpt-0
>          [[Node: save_1/RestoreV2_151 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_151/tensor_names, save_1/RestoreV2_151/shape_and_slices)]]
>          [[Node: save_1/RestoreV2_37/_1923 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1172_save_1/RestoreV2_37", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
> ```
> I don't know what problem it is. And i have tried the solution such as
> [Unsuccessful TensorSliceReader constructor](https://github.com/tensorflow/tensorflow/issues/7547) or [as suggested by ppwwyyxx](https://github.com/tensorflow/tensorflow/issues/6082#issuecomment-265055615)
> but it still not work...
> what should i do, i am a newer to tensorflow, please help me. Thx very much!

I have made it work finally. Since when i train the dataset , i think i donnot need pretrained model, but in [line39](https://github.com/YoYo000/MVSNet/blob/e1add595f259afe8783ff85e16b931a5841a7941/mvsnet/train.py#L39) of train.py 'use_pretrain' defaulte to be set as 'Ture', then it will cause error as shown above. After I change it to 'False', it works ok then.
all in all, thanks for your contribution.
