### ISSUE TITLE
About DTU's matlab code for evaluation

### ISSUE THREAD

**Issue by xiankun1995** [YoYo000/MVSNet#30]
您好！
我想用在您的论文中提到的DTU评估代码来计算distance metric。
但是我运行BaseEvalMain_web.m之后是得到了一个mat文件，请问我要怎样使用这个mat文件来得到Acc和Comp的两个值呢？
期待您的回复，谢谢。

**Comment by YoYo000** [comment]
你需要再跑一下ComputeStat_Web.m
