### ISSUE TITLE
tf.contrib.image.transform produces slightly different results

### ISSUE THREAD

**Issue by christianachilleszeisscom** [YoYo000/MVSNet#31]
Hi there, 
thanks for the mvsnet and the code.

I tried the "image.transform()" commit and compared its depth map with the results without the change. It seems, like there is a considerable difference between them (+- 2mm) and even a bias of around 1 mm between the two results. 

Can you confirm this? Feel free to use my comparison script below.

I think you can easily fix this by updating the training ``inference()`` function and the stored trained model as well. Although it would be really nice if it still produces the same results, even if used with an old trained model!

best regards Christian Achilles.

```python
import os
from preprocess import load_pfm
import numpy as np
from tensorflow.python.lib.io import file_io
import matplotlib.pyplot as plt

def compareDepthFiles(file1, file2, probFile1, probFile2):
    depth1 = load_pfm_by_name(file1)
    depth2 = load_pfm_by_name(file2)
    
#    prob1 = load_pfm_by_name(probFile1)
#    prob2 = load_pfm_by_name(probFile2)
#    mask1 = (prob1 > 0.5) & (prob1 <= 1.001)
#    mask2 = (prob2 > 0.5) & (prob2 <= 1.001)
#    depth1 *= mask1
#    depth2 *= mask2
    
    plotEvaluation(depth2-depth1, [-5, 5])
    
def load_pfm_by_name(filename):
    return load_pfm(file_io.FileIO(filename, mode='rb'))


def plotEvaluation(diff, diff_range):
        plt.set_cmap('jet')
        fig = plt.figure(figsize=(15,10))
        plt.subplot(2,1,1)
        plt.title("difference")
        plt.imshow(diff, vmin=diff_range[0], vmax=diff_range[1])
        plt.colorbar()
        
        plt.subplot(2,2,3)
        plt.title("diff distribution within the given range")
        plt.hist(np.reshape(diff, [-1]), bins=200, range=diff_range, density=True)
        
        plt.subplot(2,2,4)
        plt.title("diff distribution")
        plt.hist(np.reshape(diff, [-1]), bins=200, density=True)
    
        plt.show(fig)

folder2 = "/data/scan9/depths_mvsnet/"
folder1 = "/data/scan9/depths_ImageTransform/"

probFile1 = os.path.join(folder1, "00000000_prob.pfm")
probFile2 = os.path.join(folder2, "00000000_prob.pfm")
depthFile1 = os.path.join(folder1, "00000000.pfm")
depthFile2 = os.path.join(folder2, "00000000.pfm")


compareDepthFiles(depthFile1, depthFile2, probFile1, probFile2)
```

**Comment by YoYo000** [comment]
Hi Christian,

Thank you for pointing out the issue. I noticed this problem but I did not dig into the difference before. But now I guess I found where is the problem.

The homography warping operates on image coordinate `x, y`, however, the tf.contrib.image.transform operates on pixel coordinate `x_p, y_p`. The original homography for image coordinate is:
```x' = (a0 x + a1 y + a2) / (c0 x + c1 y + c2)```
```y' = (b0 x + b1 y + b2) / (c0 x + c1 y + c2)```
To use tf.contrib.image.transform for our warping operation, we need to derive new homography parameters for pixel coordinate:
```x'_p = (a0' x_p + a1' y_p + a2') / (c0' x_p + c1' y_p + c2')```
```y'_p = (b0' x_p + b1' y_p + b2') / (c0' x_p + c1' y_p + c2')```
Considering  `x = x_p + 0.5, y = y_p + 0.5`, the new parameters are:
```a0' = a0 - c0 / 2```
```a1' = a1 - c1 / 2```
```a2' = (a0 + a1) / 2 + a2 - (c0 + c1) / 4 - c2 / 2```
```b0' = b0 - c0 / 2```
```b1' = b1 - c1 / 2```
```b2' = (b0 + b1) / 2 + b2 - (c0 + c1) / 4 - c2 / 2```
```c0' = c0```
```c1' = c1```
```c2' = c2 + (c0 + c1) / 2```

After correcting the homography parameter, the two warping functions now produce the same output for all pixels except for image edge areas. I change the you compare function to the following and check the depth map output
```
def compareDepthFiles(file1, file2, probFile1, probFile2):
    depth1 = load_pfm_by_name(file1)
    depth2 = load_pfm_by_name(file2)
    plt.set_cmap('jet')
    plt.imshow(np.fabs(depth1 - depth2), vmin=0, vmax=1)
    plt.show()
```
Old implementation:
![image](https://user-images.githubusercontent.com/17586209/53691852-1b050c00-3d7e-11e9-9353-5b9b4601be41.png)

Corrected implemenetaiton:
![image](https://user-images.githubusercontent.com/17586209/53691862-425bd900-3d7e-11e9-99b3-157a8c251c4c.png)

Depth map of the corrected implemenetaiton is nearly the same to the homography_warping. Changes will be committed soon
