### ISSUE TITLE
why does the image coordinate is x_p = x_i + 0.5

### ISSUE THREAD

**Issue by daiszh** [YoYo000/MVSNet#38]
I notice that you gengerate pixel grid from 0.5, and then -0.5 in interplation. Since intrinsics use coordinate that start from (0,0), would that cause a problem?

**Comment by YoYo000** [comment]
Hi, 

In multi-view geometry we use image coordinate rather than pixel coordinate, and we take the top-left corner of the image as (0, 0). 

You can imagine each pixel is with width x height of 1 x 1, and then in image coordinate the center of the top-left pixel is (0.5, 0.5)
