### ISSUE TITLE
Question: testing the model on a training example

### ISSUE THREAD

**Issue by imagelina** [YoYo000/MVSNet#39]
Hello! 
Thanks, @YoYo000  a lot for your work!

I'm using your model to establish a baseline for my experiments on data augmentation for depth inference with DL. 

I do not have much experience in DL but my understanding of general principles of ML makes me believe that I should expect a good performance on a training example given that the training converged to an optimal solution. Thus, I assumed that if I take your pre-trained model and run it on an example from the training set  I should get something that looks similar to the corresponding ground truth. However, the visual assessment of the results I get  does not support my assumption. 

Here is the visualization for the test on  mvs_training/Rectified/rect_001_0_r5000.png
![scan1_train_test](https://user-images.githubusercontent.com/7021666/55719336-42df3380-59fe-11e9-849b-9f8ebebe3a0a.png)

Steps to reproduce the result:
- download dtu_training.rar as explained in the Training section of the readme
- compose the 'test_dir' as follows 
~/test_dir/images     <- mvs_training/Rectified/scan1_train
~/test_dir/cams        <- mvs_training/Cameras/train
~/test_dir/pair.txt      <- mvs_training/Cameras/pair.txt
 ~/test_dir/gt            <- mvs_training/Depths/scan1_train
- modify function `gen_pipeline_mvs_list` in preprocess.py accordingly to account for different naming of images:
line 424:` ref_image_path = os.path.join(image_folder, ('rect_%03d_0_r5000.png' % (ref_index+1)))`
line 434: `view_image_path = os.path.join(image_folder, ('rect_%03d_0_r5000.png' % (view_index+1)))`
- run the testing script with the parameters used for training:
`python test.py --dense_folder ~/test_dir/ --regularization 'GRU' --max_w 640 --max_h 512 --max_d 192 --interval_scale 1.06 --view_num 3`

Does this mean that  my assumption is wrong or did I make a mistake in my experiment somehow?

**Comment by YoYo000** [comment]
Hi @imagelina , 

For testing, the input 00000000_cam.txt should be corresponding to the 00000000.jpg. Notice that we will downsize the feature map by 4 to build the cost volume, so the camera parameters are downsized as well in the preprocessing stage (line 132~134 in test.py).

For training, I have saved the preprocessed cameras in Cameras/train, and you can find there is no preprocessing step in train.py. So if you would like to test on the training set, you could try removing line 132~134 in test.py

**Comment by imagelina** [comment]
Thanks, @YoYo000  for pointing out the scaling of the cameras. I totally missed this important part. Actually, I have overlooked some other details.  

I have made the changes you've suggested and the result makes more sense now. 

![scan1_train_test2](https://user-images.githubusercontent.com/7021666/55887835-8ed0da80-5bae-11e9-847f-ec50ce2b8036.png)
