### ISSUE TITLE
Shape mismatch after reducing test image sizes

### ISSUE THREAD

**Issue by KevinCain** [YoYo000/MVSNet#4]
From your paper, I see:

> "It is noteworthy that the training and validation on DTU dataset could be done using one consumer level GTX 1080ti graphics card (11 GB)."

After finding that 6GB of GPU RAM wasn't sufficient to complete testing with the DTU 'scan9' data set, I halved max width and height in 'test.py' in the hope of being able to test (but not _train_) with 6GB of GPU RAM, e.g.:
  'max_w' 1152-->576,
  'max_h' 864-->432

Launching test.py now fails during a Tensorflow call as the height dimension varies by one:

> ValueError: Dimension 2 in both shapes must be equal, but are 28 and 27. Shapes are [1,48,28,36,32] and [1,48,27,36,32].

I also tried scaling the (49) input images by half (1,600x1,200 --> 800x600) with the above reduced max width and height, with similar results:

> ValueError: Dimension 2 in both shapes must be equal, but are 28 and 27. Shapes are [1,48,28,36,32] and [1,48,27,36,32].

Are there other values I need to edit to successfully run resized images?

**Comment by YoYo000** [comment]
Due to the UNet structure, the input image size must be divisible by 32, so you could try change (max_w, max_h) to (576, 448)

**Comment by KevinCain** [comment]
Thanks, @YoYo000 for your very fast, helpful reply --  of course, that makes perfect sense since 'base_image_size' is 32; it also explains why only one axis gave errors as the other was already divisible by 32.

I had no problem running MVSNet on the images at 576x448 within 6GB of GPU RAM; based on nvidia-smi the max RAM used was 4878MiB.

**Comment by tatsy** [comment]
Hi @YoYo000,

I am wondering why your test code receives (1600, 1200) image in scan9 because 1200 is not the multiple of 32. According to your advice, we have to resize them to, e.g., (1280, 960) in advance?

Thank you for your help!

**Comment by YoYo000** [comment]
Hi Tatsuya,

That is because the test.py by default choose R-MVSNet (GRU
regularization). However, if you are using MVSNet (3DCNNs regularization)
then you need to make sure H and W are divisible by 32.

Best,
Yao

Tatsuya Yatagawa <notifications@github.com> 于2019年9月5日周四 下午8:15写道：

**Comment by tatsy** [comment]
Hi @YoYo000,

I was sorry that I missed the instruction in README.md and I now understand the image sizes are automatically scaled by the program by specifying `max_h` and `max_w` to it in case we use 3DCNNs instead of GRU.

Thank you!
