### ISSUE TITLE
Questions about download the pre-trained model

### ISSUE THREAD

**Issue by Gthq** [YoYo000/MVSNet#40]
Hello!
    Thanks, @YoYo000 a lot for your work! 
    When I tried to download the pre-trained models. It seems that we couldn't reach the google drive because of the "wall". Could you please provide a Baidu Netdisk version for China Mainland.
    Thank you very much!

**Comment by YoYo000** [comment]
Files are made available at:

https://pan.baidu.com/s/1Wb9E6BWCJu4wZfwxm_t4TQ#list/path=%2F

code: s2v2
