### ISSUE TITLE
点云结果在meshlab中显示很暗

### ISSUE THREAD

**Issue by Plwy** [YoYo000/MVSNet#41]
大神您好，感谢你的开源供我们学习，在此我想问一下为什么我生成的点云在meshlab中显示是如此的暗，而你们的结果都如此的清晰明亮，求帮忙看看。。
![Picture1](https://user-images.githubusercontent.com/32026411/55946562-885e6380-5c7f-11e9-9c80-0cb4426d2d00.png)
![Picture2](https://user-images.githubusercontent.com/32026411/55946574-8c8a8100-5c7f-11e9-939e-14da3a1477d5.png)

**Comment by eddienewton** [comment]
@Plwy you'll need to first compute the normals.  DepthFusion currently doesn't assign the correct normals.  Meshlab uses normals to adjust the vertex color.

In Meshlab, go to:
Filters -> Normals, Curvation, and Orientation -> Compute Normals for point sets.

This should calculate accurate normals, and color the model correctly.  You may have to refresh the Meshlab view.

**Comment by Plwy** [comment]
Thank  you @eddienewton  for your helpful and generous response.i can get the bright point cloud via Meshlab now,but i need to adjust the 'neighbor number' to  a specific value to get a satisfactory results. how can i get this result directly from mvsnet output without further adjustment?
emm...I'm a newer for this,actually.. i don't know how to compute the normals, Can I change the output directly by adjusting the test or depthfusion input parameters? if can't ,how to compute the normals?

**Comment by YoYo000** [comment]
I use the old version meshlab. In the new version meshlab you may click "Shading: None" in the right-hand side panel to get a brighter point cloud.
