### ISSUE TITLE
Evaluation on DTU dataset

### ISSUE THREAD

**Issue by xiaochi97** [YoYo000/MVSNet#45]
Hi, Yao Yao
I'm sorry to bother you because I ran into a problem when I tried to reproduce benchmarking results on DTU dataset. 
Using the pre-trained R-MVSNet model and preprocessed inputs that you provide, the evaluation results are 0.4719(mean acc) and 0.5894(mean comp). W x H x D is set to 1600 x 1200 x 256, interval_scale is set to 0.8 and prob_threshold is set to 0.3. All other settings are default. Variational depth map refinement is not applied. So, I want to know whether variational depth map refinement improves the results a lot, or some settings need to be changed.
I’m looking forward to your reply, thank you.
xiaochi

**Comment by YoYo000** [comment]
Hi @xiaochi97 

The problem might be the Fusibile. My own experiment shows that applying fusibile fusion results in a f_score ~0.52.

I suggest you implement the depth map fusion steps as mentioned in the paper (visibility fusion + average fusion), which should produce a f_score ~0.46.

**Comment by xiaochi97** [comment]
Thank you for your reply. I will try it.

**Comment by xiaochi97** [comment]
Sorry to bother you again. I have tried to add average fusion, which leads to a overall score ~0.48. But after visibility fusion is added, the results are worse. 
I implement stability-based fusion in the article (Real-Time Visibility-Based Fusion of Depth Maps), just replacing the original depth with the closest stable depth. 
So, can you offer me more details about visibility fusion?
Look forward to your reply, thank you.

**Comment by YoYo000** [comment]
I use exactly the following work flow:

1. probability filter on all depth maps
2. visibility fusion on all depth maps
3. visibility filter on all depth maps
4. average fusion on all depth maps
5. visibility filter on all depth maps

Meanwhile you need to carefully deal with the invalid pixels (e.g., out-of-range pixels and pixels with depth = 0)

**Comment by gxd1994** [comment]
> evaluation
can you share evaluation code？
