### ISSUE TITLE
Questions about evaluation results on middlebury datasets

### ISSUE THREAD

**Issue by Andyzzz** [YoYo000/MVSNet#46]
Hi,
Really appreciate your great work on both MVSNet and R-MVSNet!
I tested the R-MVSNet using the Middlebury Multiview Dataset(temple),I tried many different depth ranges ,input image pairs and different numbers of images, but the result seems always bad, could you please give some advice?

**Comment by YoYo000** [comment]
Have you tried to fuse and generate the point cloud? Maybe we can first check the point cloud. 

For middlebury data, I think we can guess the depth range from the camera center distances?

**Comment by Andyzzz** [comment]
Yes, but the result generated from the depth files was empty(0 points).

**Comment by YoYo000** [comment]
I would suggest to try the depth range by the camera center.

For example for image 0, you could set the depth range to [|c_0 - c_ave|  / 10, 3 * |c_0 - c_ave| ] and tune the value
