### ISSUE TITLE
Fusion of input with varying K values

### ISSUE THREAD

**Issue by KevinCain** [YoYo000/MVSNet#51]
@YoYo000's custom variant of Gipuma fusion, provided here, appears to assume that all input camera intrinsics share K.  For instance, input with varying principal points breaks the fusion.

Can you confirm, and perhaps suggest a workaround or an alternative fusion pipeline?

**Comment by YoYo000** [comment]
I think you have to dig into Gipuma implementation... I remember COLMAP fusion is able to accept cameras with different intrinsics, but the quality is not that good for MVSNet.

**Comment by KevinCain** [comment]
Yes, I can confirm that Gipuma fusion assumes all cameras share intrinsics.  I'll have a look!
