### ISSUE TITLE
Testing on tanks and temples dataset

### ISSUE THREAD

**Issue by DiscoDiscoBoomBoom** [YoYo000/MVSNet#53]
Hi, I try to evaluate you method on DTU dataset and works perfectly. But when trying your method on tanks and temples dataset, dimensions of input didn't match:
shape[0] = [1,136,240,64] vs. shape[1] = [1,135,240,64]
I am glad receive your apply

**Comment by Nekomiya-fubuki** [comment]
Hi,I meet this error,too. and I don't how to correct.Did you solve this problem?
