### ISSUE TITLE
some confused detail when training

### ISSUE THREAD

**Issue by MASTERCHIEF343** [YoYo000/MVSNet#54]
Hi, thanks to your code.
      First, I follow your readme 'python train.py --regularization 'GRU', and I change the flag 'use_pretrain' to False, so my first question is that is this model need a pre-trained weights?
      Second, I use ubuntu18.04, tensorflow1.6.0,gtx1080, I think my memory is enough, but after first epoch, the program has been killed.So I change the max_d and interval_scale.So I'm wonder that if this has some influence on result?Should I use some bigger memeory?

**Comment by YoYo000** [comment]
The model can be trained from scratch, the "--use_pretrain" is just an interface for your convenience.

I would not suggest changing the hyperparameters during training. From my experiments, 8GB is enough for MVSNet training, but R-MVSNet requires at least 11GB memory.
