### ISSUE TITLE
colmap数据转化

### ISSUE THREAD

**Issue by FD-MINGJIE** [YoYo000/MVSNet#55]
(MVSNet) mj@mj:~/MVSNet-master/mvsnet$ python colmap2mvsnet.py --dense_folder /home/mj/colmap/dataset/dense/0
intrinsic[1]
 [[2.92722e+03 0.00000e+00 8.00000e+02]
 [0.00000e+00 2.92722e+03 6.00000e+02]
 [0.00000e+00 0.00000e+00 1.00000e+00]]

extrinsic[1]
 [[ 0.95969319  0.14333676 -0.24175088  2.11708   ]
 [-0.26888973  0.71855134 -0.64139057  1.67252   ]
 [ 0.08177545  0.68054252  0.72813065  1.69354   ]
 [ 0.          0.          0.          1.        ]]

depth_ranges[1]
 (5.513600130037293, 0.0027651527008935423, 918.157205263011, 8.04967985331428)

view_sel[0]
 [(9, 1722.2056093185822), (10, 1466.256031899926), (1, 833.5377048567944), (8, 766.1517870794412), (2, 740.7407016122528), (14, 418.4869017827645), (13, 361.9854804660677), (12, 258.1712719763748), (7, 154.25892034175422), (15, 146.84946368338626)]

/home/mj/colmap/dataset/dense/0/cams already exist.
Traceback (most recent call last):
  File "colmap2mvsnet.py", line 439, in <module>
    shutil.copyfile(os.path.join(image_dir, images[i+1].name), os.path.join(renamed_dir, '%08d.jpg' % i))
  File "/home/mj/anaconda3/envs/MVSNet/lib/python2.7/shutil.py", line 83, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
shutil.Error: `/home/mj/colmap/dataset/dense/0/images/00000003.jpg` and `/home/mj/colmap/dataset/dense/0/images/00000003.jpg` are the same file
问题：
生成了cam和impair，但是cam里面只有49个，您的scan测试集cam有63个；这个error怎么修正呢？
谢谢！！！

**Comment by YoYo000** [comment]
Hi,

dtu数据集的前49个相机的位置更加靠近物体，测试的时候一般都只用前49张照片，后面的照面不加入重建
