### ISSUE TITLE
Speedup with the tf.contrib.image method

### ISSUE THREAD

**Issue by KevinCain** [YoYo000/MVSNet#57]
@YoYo000 suggested he'd seen ~200% speedup given the tf.contrib.image method, however in my tests the timing is roughly the same.

For example, I do note that for ‘GRU’ timing I see **1:27** total for a set of 48 images, ‘CNN3D’ by contrast is **2:23** for the same 48 image set; however the time savings in the former is all in initialization time for the network, while the run time per image is slightly higher for the GRU case.

Is this in keeping with your observations?  Thanks for any suggestions.

**Comment by YoYo000** [comment]
The per image processing times are roughly the same for "3DCNNs" and "GRU".

On the other hand, using "tf.contrib.image" for warping will accelerate both "3DCNNs" and "GRU". For example, the original implementation will take ~4s/view for processing.

**Comment by KevinCain** [comment]
Thanks for this helpful clarification!

My observation was that you saw ~200% runtime improvement with (https://github.com/YoYo000/MVSNet/commit/d0b9ac6601143e0676014ba50891810da10514c7) and ~30% with prefetch buffering (https://github.com/YoYo000/MVSNet/commit/bc6d0ed992cc294a7f91888ec7c14214be7158a1).

For some reason I'm seeing similar performance comparing builds from these commits v. earlier MVSNet.  However, all of this is anecdotal as I haven't tested on many machines.  If I can provide some numbers, I'll reopen this issue.  In the mean time, thank you as always.
