### ISSUE TITLE
questions about the training and testing for new dataset

### ISSUE THREAD

**Issue by lonl** [YoYo000/MVSNet#58]
hi, 很感谢分享这一很棒的工作;
1）我们尝试用该项目去训练航拍数据。首先我们利用colmap产生的dense数据作为GT labels，然后将colmap生成的相机位姿和dense depth（有空洞、不完整、也没有过滤outliers）的数据转换成Mvsnet所需要的数据格式进行训练，效果并不理想，请问可能存在的原因会有哪些？如果是GT label的问题，如何生成完整可用的训练数据？

２) 在进行点云融合的时候，有一个normal_thresh这个参数该如何进行选择？

谢谢～

**Comment by YoYo000** [comment]
已经回复你的邮件了 :)

**Comment by lonl** [comment]
@YoYo000 谢谢～

**Comment by ChenLiufeng** [comment]
> hi, 很感谢分享这一很棒的工作;
> 1）我们尝试用该项目去训练航拍数据。首先我们利用colmap产生的dense数据作为GT labels，然后将colmap生成的相机位姿和dense depth（有空洞、不完整、也没有过滤outliers）的数据转换成Mvsnet所需要的数据格式进行训练，效果并不理想，请问可能存在的原因会有哪些？如果是GT label的问题，如何生成完整可用的训练数据？
> 
> ２) 在进行点云融合的时候，有一个normal_thresh这个参数该如何进行选择？

> 
> 谢谢～

我们想尝试用这个项目去训练农作物（比如植物幼苗）数据，也遇到上面的问题，麻烦给予宝贵建议，谢谢！
