### ISSUE TITLE
Score values in view selection

### ISSUE THREAD

**Issue by KevinCain** [YoYo000/MVSNet#6]
I'm attempting to supply my own data, and was hoping for a little explanation of the score values read from the view selection file.  How should we compute these values?  I see they're read, but I don't see if and where they're used.  Any helpful hints would be welcome.

As an example, here in 'pair.txt' the scale weights are in bold following each of the 10 IDs:

> 49
> 0
> 10 **10 2346.41** 1 **2036.53** 9 **1243.89** 12 **1052.87** 11 **1000.84** 13 **703.583** 2 **604.456** 8 **439.759** 14 **327.419** 27 **249.278**

**Comment by YoYo000** [comment]
The scores will not be used in MVSNet. You could safely ignore them :)

**Comment by KevinCain** [comment]
Thank you -- good to hear.
