### ISSUE TITLE
Unclear definitions of DEPTH_MIN, DEPTH_MAX, DEPTH_NUM and DEPTH_INTERVAL

### ISSUE THREAD

**Issue by frozenscrypt** [YoYo000/MVSNet#60]
Hi, I'm trying to use preexisting depth maps for 7 scenes dataset. I've extrinsic and intrinsic parameters of the images but I don't understand how to get DEPTH_MIN, DEPTH_MAX, DEPTH_NUM and DEPTH_INTERVAL to add them to the cam files. Please help!

Thanks.

**Comment by YoYo000** [comment]
Hi @frozenscrypt , if you have the GT depth map, you can simply find the max and min depth value of the depth map and set it to DEPTH_MAX DEPTH_MIN. Then you can set D = 256 and DEPTH_INTERVAL = (DEPTH_MAX - DEPTH_MIN) / D.
