### ISSUE TITLE
questions about inverse depth

### ISSUE THREAD

**Issue by Yeeef** [YoYo000/MVSNet#61]
Hi,
really appreciate your great work on R-MVSNet!
I read from your paper that you formalize the problem as a classification problem since the **inverse depth** is adopted. And from your code, I find the function `get_homographies_inv_depth` is for inverse depth sampling and homography building. But in `inference_prob_recurrent`, it seems that the old `get_homographies` is in use. Moreover, in `inference_winner_take_all`, which is a evaluate-phase function, the new `get_homographies_inv_depth` is in use.
I am a little confused, I think in both training and testing, we should use `get_homographies_inv_depth`. Or maybe I just missed something.

Thanks in advance!

**Comment by YoYo000** [comment]
Hi @Yeeef , you are correct that I use uniform sample for training but inverse sample for testing. This setting should be ok as during testing we just use the winner take all to select the best depth hypothesis.

Of cause, it would be more consistent if we change the depth sample also to inverse during training.

**Comment by Yeeef** [comment]
Got it, thank you!
