### ISSUE TITLE
Can't get point cloud

### ISSUE THREAD

**Issue by HaloKim** [YoYo000/MVSNet#62]
Thank you your code.
When I use depthfusion.py
I have a permission denied error
How set fusibile_exe_path ?
I'm just set CMakeFiles folder directory like this(parser.add_argument('--fusibile_exe_path', type=str, default = '/home/git/CMakeFiles'))

/home/git/anaconda2/bin/python2.7 /home/git/MVSNet-master/mvsnet/depthfusion.py
filter depth map with probability map
Convert mvsnet output to gipuma input
Run depth map fusion & filter
/home/git/CMakeFiles -input_folder /home/git/TEST_DATA_FOLDER/points_mvsnet/ -p_folder /home/git/TEST_DATA_FOLDER/points_mvsnet/cams/ -images_folder /home/git/TEST_DATA_FOLDER/points_mvsnet/images/ --depth_min=0.001 --depth_max=100000 --normal_thresh=360 --disp_thresh=0.25 --num_consistent=3.0
**sh: 1: /home/git/CMakeFiles: Permission denied**

Process finished with exit code 0

Right Result ?
![스크린샷, 2019-07-10 14-43-42](https://user-images.githubusercontent.com/44603549/60943501-2f0adc80-a321-11e9-8a3c-4cd0347f4160.png)

**Comment by YoYo000** [comment]
Have you successfully compile the fusibile? The executable should be at fusibile/fusibile.

**Comment by HaloKim** [comment]
> Have you successfully compile the fusibile? The executable should be at fusibile/fusibile.

Thank you !
I understand my mistake !!
Solved it !

**Comment by YuzuruHanyu520** [comment]
Hi, I also meet this problem, when I run the next two instruction, I can get the same result as you,but I can get the final .ply files, would you dive me some advices, thank you very much!
$ python depthfusion.py --dense_folder /home/omnisky/Downloads/MVSNet-master/test621/ours/scan15 --fusibile_exe_path /home/omnisky/Downloads/MVSNet-master/fusibile --prob_threshold 0.3
$ python depthfusion.py --dense_folder /home/omnisky/Downloads/MVSNet-master/test621/ours/scan15 --fusibile_exe_path /home/omnisky/Downloads/MVSNet-master/fusibile/=CMakeFiles/fusibile.dir --prob_threshold 0.3

**Comment by HaloKim** [comment]
> Hi, I also meet this problem, when I run the next two instruction, I can get the same result as you,but I can get the final .ply files, would you dive me some advices, thank you very much!
> $ python depthfusion.py --dense_folder /home/omnisky/Downloads/MVSNet-master/test621/ours/scan15 --fusibile_exe_path /home/omnisky/Downloads/MVSNet-master/fusibile --prob_threshold 0.3
> $ python depthfusion.py --dense_folder /home/omnisky/Downloads/MVSNet-master/test621/ours/scan15 --fusibile_exe_path /home/omnisky/Downloads/MVSNet-master/fusibile/=CMakeFiles/fusibile.dir --prob_threshold 0.3

Did you solve this problem ?
You must make fusibile file.

**Comment by Nekomiya-fubuki** [comment]
Hi,I  meet this erro ,too.but I don't konw how to solve it.I'm sure that I make fusibile file
(neucon) u@u-Precision-7920-Tower:~/Documents/MVSNet-master/fusibile-master/build$ make
[ 33%] Building NVCC (Device) object CMakeFiles/fusibile.dir/fusibile_generated_fusibile.cu.o
/home/u/Documents/MVSNet-master/fusibile-master/fusibile.cu(178): warning: variable "used_list" was set but never used

/home/u/Documents/MVSNet-master/fusibile-master/fusibile.cu(372): warning: variable "grid_size" was set but never used

/home/u/Documents/MVSNet-master/fusibile-master/fusibile.cu(375): warning: variable "block_size" was set but never used

ptxas info    : 64576 bytes gmem, 72 bytes cmem[3]
ptxas info    : Compiling entry function '_Z8fusibileR11GlobalStatei' for 'sm_60'
ptxas info    : Function properties for _Z8fusibileR11GlobalStatei
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 48 registers, 332 bytes cmem[0], 20 bytes cmem[2]
/home/u/Documents/MVSNet-master/fusibile-master/fusibile.cu: In function ‘void copy_point_cloud_to_host(GlobalState&, int, PointCloudList&)’:
/home/u/Documents/MVSNet-master/fusibile-master/fusibile.cu:289:7: warning: ‘texture4[3]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             float texture4[4];
       ^     ~~
/home/u/Documents/MVSNet-master/fusibile-master/fusibile.cu:289:7: warning: ‘texture4[1]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/u/Documents/MVSNet-master/fusibile-master/fusibile.cu:289:7: warning: ‘texture4[0]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/u/Documents/MVSNet-master/fusibile-master/fusibile.cu:289:7: warning: ‘texture4[2]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
Scanning dependencies of target fusibile
[ 66%] Building CXX object CMakeFiles/fusibile.dir/main.cpp.o
[100%] Linking CXX executable fusibile
[100%] Built target fusibile

but there still is a problem.I use this instruction 
$ python depthfusion.py --dense_folder /home/u/Documents/MVS_TRANING/TEST_DATA_FOLDER/scan9 --fusibile_exe_path /home/u/Documents/MVSNet-master/fusibile-master/fusibile.h --prob_threshold 0.8
filter depth map with probability map
Convert mvsnet output to gipuma input
Run depth map fusion & filter
/home/u/Documents/MVSNet-master/fusibile-master/fusibile.h -input_folder /home/u/Documents/MVS_TRANING/TEST_DATA_FOLDER/scan9/points_mvsnet/ -p_folder /home/u/Documents/MVS_TRANING/TEST_DATA_FOLDER/scan9/points_mvsnet/cams/ -images_folder /home/u/Documents/MVS_TRANING/TEST_DATA_FOLDER/scan9/points_mvsnet/images/ --depth_min=0.001 --depth_max=100000 --normal_thresh=360 --disp_thresh=0.25 --num_consistent=3.0
sh: /home/u/Documents/MVSNet-master/fusibile-master/fusibile.h: Permission denied

How can I sovle it?
