### ISSUE TITLE
test.py error with dsize.empty()

### ISSUE THREAD

**Issue by HaloKim** [YoYo000/MVSNet#63]
Thanks your source code.
I'm trying to execute your code with using other data set
I'm using vertical image while your test image is horizontal image.
and i got error like this
tensorflow.python.framework.errors_impl.UnknownError: error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/modules/imgproc/src/resize.cpp:4050: error: (-215:Assertion failed) !dsize.empty() in function 'resize'
Is it because i'm using vertical image? or i made another mistake?

**Comment by seokhyeonSong** [comment]
I think your image is not enough big size to resize..

**Comment by HaloKim** [comment]
InvalidArgumentError (see above for traceback): ConcatOp : Dimensions of inputs should match: shape[0] = [1,16,20,64] vs. shape[1] = [1,15,20,64]
	 [[Node: 2dconcat5_0 = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](transpose_29, 2dconv3_2/relu, Reshape_126/shape/0)]]
	 [[Node: while/RefExit/_271 = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_9852_while/RefExit", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

I have a ArgumentError
How solve it ?

**Comment by YoYo000** [comment]
What is your image size?

Meanwhile if you change the max_h max_w, you must make sure that they are divisible by 16 (to fit U-Net strutures).

**Comment by HaloKim** [comment]
@YoYo000 
Thanks your advise.

but occur other problem
when i use colmap2mvs

![스크린샷, 2019-07-19 16-00-29](https://user-images.githubusercontent.com/44603549/61515944-c3babc00-aa3e-11e9-969e-94acf9343638.png)

what should i do ?

**Comment by YoYo000** [comment]
@HaloKim have you solved the problem?

If you still get stuck you could send your colmap file to me

**Comment by HaloKim** [comment]
I cant's solved it.
It seems like occur error during colamp converting.
Different the number of 'Number of camera' and 'images'.
