### ISSUE TITLE
Problem with train my datasets.

### ISSUE THREAD

**Issue by HaloKim** [YoYo000/MVSNet#65]
Hi Yao Yao.
Thank you, MVSNet code.
But I have problem with my dataset.
Your **Train.py** Require depth_map, cam.txt.
So, Doesn't Above file created in post-processing ?
How, Why this file getting to Train.py ?
How use my dataset in your MVSNet train, When I have only jpg file.

**Comment by YoYo000** [comment]
If you want to train on your own data then you need to prepare [reference_image, source_images, reference_camera, source_cameras, reference_gt_depthmap].

To integrate into the current pipeline, I think the easiest way is to generate a training sample list (like gen_dtu_resized_path() in preprocess script) on your own data, and change the image input size and depth sample number correspondingly.

**Comment by HaloKim** [comment]
Thanks !
