### ISSUE TITLE
Depth Fusion

### ISSUE THREAD

**Issue by victorgmlyra** [YoYo000/MVSNet#74]
Hello,
Do you know if there is another good depth fusion algorithm that works well with MVSNet other than fusible (gipuma)?
Thanks!

**Comment by YoYo000** [comment]
Hi @victorgmlyra,

Colmap provides a depth fusion algorithm, also I find there is a pytorch implementation of MVSNet: https://github.com/xy-guo/MVSNet_pytorch. The author implements the depth map fusion themselves and maybe you could have a try?

**Comment by victorgmlyra** [comment]
Thanks, @YoYo000 !

I tried the depth fusion from the pytorch implmentation and it worked!  👍
