### ISSUE TITLE
How to make pair.txt when testing R-MVSNet with our own multi-view dataset

### ISSUE THREAD

**Issue by gimunum** [YoYo000/MVSNet#76]
Hello. I am testing R-MVSNet. I have succeeded in learning R-MVS Net with sample training dtu dataset and also succeeded in testing with  dataset scan9. Moreover, I also sucessfully completed to run depthfusion.py.  As a last step, I am trying to test R-MVS Net with our multi-view test sequences captured by 4x4 multi-view camera array. I also created 0000000X_cam.txt files in cams directory.  However, I am blocked in handing pair.txt.  Coudl you anyone tell me how to make pair.txt? Should it be created by COLMAP software?  I think that this file may not be created by mannually, but I have no idea how to create it automatically. 
Thanks in advance.

**Comment by YoYo000** [comment]
Hi @gimunum 

If you have a SfM reconstruction, you could follow the view selection part in our paper to generate the pair.txt file.

Also, if you generate the SfM using COLMAP, we provided a simple script colmap2mvsnet.py to generate the cameras and pair files.

**Comment by gimunum** [comment]
Dear Yao.

Thanks for the reply. I have generated pair.txt from COLMAP, I converted them with colmap2mvsnet.py. Now I am doing tests with R-MVSNet with our dataset.

I will ask you again if there is a question to ask.

Thanks

Best Regards,

Gi-Mun Um
