### ISSUE TITLE
论文中公式问题

### ISSUE THREAD

**Issue by ZhouXiner** [YoYo000/MVSNet#77]
在18年的MVSNet文章中，part 3.2的公式一有误，H的求解最后应当是K1的逆而不是转置

**Comment by YoYo000** [comment]
Thanks! It is indeed a typo.

**Comment by yangfengt123** [comment]
能问一下这个公式是怎么推导的吗？ 我推了一下 得到的是下图中的样子， 感觉和论文中的不太一样啊。我看了引文plane sweeping 但是还是没理解到 这个公式1是怎么推导的

多谢了

![1761580097067_ pic](https://user-images.githubusercontent.com/34109262/73149318-b554f900-408e-11ea-9ac8-4e439f684132.jpg)

**Comment by kwea123** [comment]
我最近看到也在想。刚看到的时候还想怎么可能式子那么漂亮，结果自己导出来根本不是那样子！
他的论文里写的公式是**错的**！！还导致了一些之后论文就直接抄他的，结果大家都是错的。
虽然论文是错的，但是他的implementation是对的，因为用了完全不一样的式子。。。
就是这边，不知道正确的公式的话完全不知道是什么
https://github.com/YoYo000/MVSNet/blob/3ba7307a104748cf0031a48e61318702fc85700f/mvsnet/homography_warping.py#L29-L33
大体来说你的想法是对的，但有些细节错了，我之后会在我的youtube频道发布正确推导影片。我是参考了[MVSNet_pytorch](https://github.com/xy-guo/MVSNet_pytorch/blob/master/models/module.py#L96)的implementation才想到的，他的implementation也是正确的而且也比较好理解。

**Comment by kwea123** [comment]
正確推導的影片（45:02開始）
https://www.youtube.com/watch?v=zmE_kj-Gh84

**Comment by yangfengt123** [comment]
谢谢分享，已订阅

**Comment by YoYo000** [comment]
> 正確推導的影片（45:02開始）
> https://www.youtube.com/watch?v=zmE_kj-Gh84

Hi，论文中的公式应该有两个错误，

1. K_1^T应该改成K_1^{-1}

2. t应该改为c（相机中心）。

谢谢指出错误，我看了你的推导，应该和上面两点也是对应的。因为plane sweeping中的homography不是一个新的推导，所以我们写论文的时候没有仔细检查。抱歉给大家带来了这么多困扰！

**Comment by kwea123** [comment]
感謝你的回覆。後來我發現用3d點的warping來想會比較容易，也就是先用K-1投影回3d，然後再用extrinsic轉換到source view後用K投影，比起homography來說會比較好理解跟implement。
