### ISSUE TITLE
where is the code implementing depth map filter using geometric criteria as stated in paper?

### ISSUE THREAD

**Issue by TruongKhang** [YoYo000/MVSNet#79]
Hi, can you show me the code for implementing the depth map filtering? I only found that you use a threshold and remove any pixels with probability lower than threshold in file `depthfusion.py`

**Comment by YoYo000** [comment]
Hi,

depthfusion.py will call Gipuma for filter and fusion. If you are interested, you may refer to Gipuma's implementation.
