### ISSUE TITLE
Which Tensorflow version should I use ?

### ISSUE THREAD

**Issue by phongnhhn92** [YoYo000/MVSNet#80]
Hello,
I am trying to run your code but somehow I received tons of deprecation errors related to Conv2D. Right now I am using Tensorflow 1.14.
`. Cause: converting <bound method Conv2D.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f3869c94550>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Conv2D.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f3869cbb750>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv2D.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f3869cbb750>>: AssertionError: Bad argument number for Name: 3, expecting 4
`

**Comment by YoYo000** [comment]
Hi @phongnhhn92, 

The code is first implemented using TF 1.4. In the current TF 1.14 version there will be the ugly warnings, but it should still be ok

**Comment by Qtodd** [comment]
Hello @phongnhhn92 Which version of TF did you choose at last ?

**Comment by phongnhhn92** [comment]
Thanks !
