### ISSUE TITLE
question about cost volume building

### ISSUE THREAD

**Issue by MASTERCHIEF343** [YoYo000/MVSNet#82]
Hi, thanks to the code.After Diﬀerentiable Homography, you add reference image feature and target image feature to build one volume?I see the code "ave_feature = tf.assign_add(ave_feature, warped_view_feature)".

**Comment by YoYo000** [comment]
![image](https://user-images.githubusercontent.com/17586209/69529238-d627a200-0faa-11ea-8c83-b931039bd643.png)

**Comment by MASTERCHIEF343** [comment]
Oh, I see.And for building cost volume, in different depth planes, is it right that you concatenate reference feature and target feature?

**Comment by YoYo000** [comment]
No. We calculate the element-wise variance among all features (the reference feature and warped source features).

**Comment by MASTERCHIEF343** [comment]
Thank you
