### ISSUE TITLE
Don't get the .ply file when i try use COLMAP to get MVSNet's input on scan9

### ISSUE THREAD

**Issue by ApeCoding** [YoYo000/MVSNet#83]
Hi:
        I use CLOMAP on scan9 image,  there are no problem, and i get the depth map and probability map,but when i fusion the depth,there are none point find, even i set the prob_threshold to 0.01.
`python ./MVSNet/mvsnet/depthfusion.py --dense_folder ./scan9/dense --fusibile_exe_path ./fusibile/build/fusibile --prob_threshold 0.01`
       After this commond,i get this results:
`Fusing points       Processing camera   Found 0.00 million points ...`
     when i looking at the probability map, the color of the picture almost blue, the probability value are too small. 
     i don't get .ply file,there is an ERROR:
     `Error:  no kernel image is available for execution on the device`
     i don't know how to fix it. Can you solve this problem? thx! 

I use GRU to get the depth map.

---
你好：
        非常不好意思哈，英语不太好，表述可能不是很清楚。
        我用COLMAP提取scan9图片的特征点，匹配，获得稀疏重建，之后矫正图像，转换输出为txt，最后用你这边提供的.py脚本转换为MVSNet的输入。然后用MVSNet 'GRU'获得深度图和概率图，发现概率图中的概率值非常小，但也有很少的部分为0.8左右，其他的基本上都在0.05左右，呈现出来的结果是几乎全是蓝色的。
       在做fusion的时候，发现没有点...  ./ply文件没有生成。
       报了一个错：
`Error:  no kernel image is available for execution on the device`
不知道这是怎么回事，希望能够得到你的回答，非常感谢！

**Comment by ApeCoding** [comment]
i use GTX2060super 8G

**Comment by ys1215** [comment]
the same problem as you, how did you solve it?
