### ISSUE TITLE
How to convert depth map to real depth value?

### ISSUE THREAD

**Issue by liujie183** [YoYo000/MVSNet#96]
Hi,
I've been doing a free viewpoint video research recently, and depth estimation is a key step of FVV pipeline. I've tryed to use MVSNet to do the depth estimation work, but don't know how to convert the resulting depth estimation result to real depth value, does anyone know how to get the real depth value?

**Comment by BingEdison** [comment]
Did you solve issue ? Please help  I have projected points but there is a curve to all points projected that is absent in fusibile output

**Comment by liujie183** [comment]
> Did you solve issue ? Please help I have projected points but there is a curve to all points projected that is absent in fusibile output

It seems the pfm file store the float-point format depth information already
